/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package example;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class Exhibition extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    public Exhibition() {
        initComponents();
        setSize(800, 600);
    }
    
    void connectionDb(){
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
           // return conn;
        }catch(ClassNotFoundException e){
            //JOptionPane.showMessageDialog(null, e);
            System.out.println("error class conn" + e);
        }catch (SQLException s){
            System.out.println("error sqls conn" + s);
        }
        //return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        number = new javax.swing.JLabel();
        jTextField_number = new javax.swing.JTextField();
        type = new javax.swing.JLabel();
        jTextField_type = new javax.swing.JTextField();
        floor = new javax.swing.JLabel();
        jTextField_floor = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        jTextField_date = new javax.swing.JTextField();
        jButton_INSERT = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        delbynum = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        delete_all = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        search_num = new javax.swing.JTextField();
        search_by_number = new javax.swing.JButton();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ex = new javax.swing.JTable();
        jButton_showall = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Vivaldi", 3, 24)); // NOI18N
        jLabel1.setText("Exhibition Register");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        name.setFont(new java.awt.Font("Vivaldi", 3, 14)); // NOI18N
        name.setText("Name");

        number.setFont(new java.awt.Font("Vivaldi", 3, 14)); // NOI18N
        number.setText("Number");

        type.setFont(new java.awt.Font("Vivaldi", 3, 14)); // NOI18N
        type.setText("Type");

        floor.setFont(new java.awt.Font("Vivaldi", 3, 14)); // NOI18N
        floor.setText("Floor");

        date.setFont(new java.awt.Font("Vivaldi", 3, 14)); // NOI18N
        date.setText("Date");

        jButton_INSERT.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton_INSERT.setText("INSERT");
        jButton_INSERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_INSERTActionPerformed(evt);
            }
        });

        jButton_update.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton_update.setText("UPDATE");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        delbynum.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        delbynum.setText("DELETE BY NUMBER");
        delbynum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbynumActionPerformed(evt);
            }
        });

        delete_all.setFont(new java.awt.Font("Calibri", 3, 11)); // NOI18N
        delete_all.setText("DELETE  ALL");
        delete_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_allActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Vivaldi", 3, 14)); // NOI18N
        jLabel7.setText("ENTER NUMBER ");

        search_by_number.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        search_by_number.setText("SEARCH BY NUMBER");
        search_by_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_numberActionPerformed(evt);
            }
        });

        close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        close.setForeground(new java.awt.Color(0, 51, 51));
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        minimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minimize.setForeground(new java.awt.Color(0, 51, 51));
        minimize.setText("_");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        jTable_ex.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable_ex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name", "Type", "Floor", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable_ex);

        jButton_showall.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton_showall.setText("Show All Data");
        jButton_showall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_showallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(close)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delbynum))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(number)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_number, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField_type, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField_floor)
                                .addComponent(jTextField_date)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton_INSERT)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_update))
                                .addComponent(jTextField_name))))
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search_num, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search_by_number))
                    .addComponent(delete_all, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_showall, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(close)
                    .addComponent(minimize))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search_num, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search_by_number))
                        .addGap(18, 18, 18)
                        .addComponent(delete_all)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(type))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_floor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(floor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_INSERT)
                            .addComponent(jButton_update))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delbynum))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_showall)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
         Exhibition e  = new Exhibition();
        e.setVisible(true);
        e.pack();
        e.setLocationRelativeTo(null);
        e.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton_INSERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_INSERTActionPerformed
        String ex_number = jTextField_number.getText();
        int number = Integer.parseInt(ex_number);
       String ex_name = jTextField_name.getText();
       String ex_date = jTextField_date.getText();
       String type = jTextField_type.getText();
       String floor = jTextField_floor.getText();
       
       connectionDb();
       
       String sql = "insert into exhibition (ex_name,type,ex_date,ex_number,floor) values (?,?,?,?,?)";
       
       try{
           ps = conn.prepareStatement(sql);
           ps.setString(1, ex_number);
           ps.setString(2, ex_name);
           ps.setString(3, ex_date);
           ps.setString(4, type);
           ps.setString(5, floor);
           
           ps.executeUpdate();
           
           JOptionPane.showMessageDialog(null, "inserted successfully");
          // show_data();/////////////////////////////////////////////////////////////////////////////////??????
           //jTextField_number.setText("");
           //jTextField_name.setText("");
           //jTextField_date.setText("");
           //jTextField_type.setText("");
           //jTextField_floor.setText("");
           //conn.close();
           
           
           
       
       }catch(SQLException e){
           System.out.println("error in sql" + e);
           
       }
       
       
    }//GEN-LAST:event_jButton_INSERTActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void jButton_showallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_showallActionPerformed
        show_data();
    }//GEN-LAST:event_jButton_showallActionPerformed
        void show_data(){
        connectionDb();
        //String ex_number = jTextField_number.getText();
        //int number = Integer.parseInt(ex_number);
        String sql = "select * from exhibition";
        
        try{
            ps = conn.prepareStatement(sql);
           // ps.setInt(1, number);
           rs = ps.executeQuery();
           jTable_ex.setModel(DbUtils.resultSetToTableModel(rs));
           rs.close();
           conn.close();
           
           while(rs.next()){
               String name = rs.getString("name");
               int num = rs.getInt("number");
               String type = rs.getString("type");
               String floor = rs.getString("floor");
               String date = rs.getString("date");
               
           jTextField_number.setText(num +"");
           jTextField_name.setText(name +"");
           jTextField_date.setText(date+"");
           jTextField_type.setText(type+"");
           jTextField_floor.setText(floor+"");
               
               
           }
            //JOptionPane.showMessageDialog(close, ps);
        }
        catch(SQLException e){
            System.out.println("error delete: " + e);
            
            
            
        }
        
        }
    private void delete_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_allActionPerformed
       connectionDb();
        String sql = "delete from exhibition";
        try{
            ps = conn.prepareStatement(sql);
           rs = ps.executeQuery();
           JOptionPane.showMessageDialog(null, "delete successfully");
           conn.close();
        }
        catch(SQLException e){
            System.out.println("error delete: " + e);
        }
    }//GEN-LAST:event_delete_allActionPerformed

    private void search_by_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_numberActionPerformed
         connectionDb();
        String ex_number = jTextField_number.getText();
        int number = Integer.parseInt(ex_number);
        String sql = "select ex_number,ex_name,type,floor,date from exhibition where id = ?";
        
        try{
            ps = conn.prepareStatement(sql);
            ps.setInt(1, number);
            
           rs = ps.executeQuery();
           
           while(rs.next()){
               String ex_name = rs.getString("name");
               //int ex_number = rs.getInt("number");
               String type = rs.getString("type");
               String floor = rs.getString("floor");
               String date = rs.getString("date");
               
           jTextField_number.setText(ex_number +"");
           jTextField_name.setText(ex_name +"");
           jTextField_date.setText(date+"");
           jTextField_type.setText(type+"");
           jTextField_floor.setText(floor+"");
               
               
           }
            //JOptionPane.showMessageDialog(close, ps);
            conn.close();
        }
        catch(SQLException e){
            System.out.println("error search: " + e);
        }
    }//GEN-LAST:event_search_by_numberActionPerformed

    private void delbynumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbynumActionPerformed
        String ex_number = jTextField_number.getText();
        int number = Integer.parseInt(ex_number);
        
        
        connectionDb();
        String sql = "delete from exhibition where ex_num = ?";
        //String str_number = txtDelete.getText();
       // int num = Integer.parseInt(sql)
        try{
            ps = conn.prepareStatement(sql);
            ps.setInt(1, number); 
           rs = ps.executeQuery();
           JOptionPane.showMessageDialog(null, "delete successfully");
           ///////////////////////////////////// txtDelete.setText("");
          // jTextField_numberDelete.setText("")
           conn.close();
        }
        catch(SQLException e){
            System.out.println("error delete: " + e);
        }
    }//GEN-LAST:event_delbynumActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        String ex_number = jTextField_number.getText();
        int number = Integer.parseInt(ex_number);
       String ex_name = jTextField_name.getText();
       String ex_date = jTextField_date.getText();
       String type = jTextField_type.getText();
       String floor = jTextField_floor.getText();
       
       connectionDb();
       String sql =  "update employee set name = ?, age= ?, phone=? where id = ?";
       try{
           conn.prepareStatement(sql);
           ps.setInt(1, number); 
           ps.setString(2, ex_name);
           ps.setString(3, ex_date);
           ps.setString(4, type);
           ps.setString(5, floor);
           ps.executeUpdate();
           JOptionPane.showMessageDialog(null,"update successfully");
           
           jTextField_number.setText(ex_number +"");
           jTextField_name.setText(ex_name +"");
           jTextField_date.setText(date+"");
           jTextField_type.setText(type+"");
           jTextField_floor.setText(floor+"");
           
           conn.close();
           
       }catch(SQLException e){
           System.out.println("error update" + e);
       }
       
    }//GEN-LAST:event_jButton_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exhibition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exhibition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exhibition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exhibition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exhibition().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JLabel date;
    private javax.swing.JButton delbynum;
    private javax.swing.JButton delete_all;
    private javax.swing.JLabel floor;
    private javax.swing.JButton jButton_INSERT;
    private javax.swing.JButton jButton_showall;
    private javax.swing.JButton jButton_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_ex;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField_date;
    private javax.swing.JTextField jTextField_floor;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_number;
    private javax.swing.JTextField jTextField_type;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel name;
    private javax.swing.JLabel number;
    private javax.swing.JButton search_by_number;
    private javax.swing.JTextField search_num;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
